---
title: "UFO Sightings Report"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridisLite)
library(forecast)
library(arules)
library(highcharter)
library(sf)
library(treemap)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(maps)
library(shiny)


thm = 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

```



```{r}
ufo = read_csv("./data/ufo_clean.csv")

ufo_subset = ufo |>
  select(city, state, date_time, shape, city_latitude, city_longitude, dist, location)

ufo_subset = ufo_subset |>
  mutate(date = as.Date(date_time),
         year_month = format(date, "%Y-%m"))

monthly_trends = ufo_subset |>
  count(year_month) |>
  arrange(year_month)

```



Column {data-width=600}
-----------------------------------------------------------------------

### Report by Year



```{r}
ufo_subset |>
  mutate(
    year = format(as.Date(date), "%y")) |>
  count(year) |>
  ggplot(aes(x = as.numeric(year), y = n)) +
  geom_line(color = "blue") +
  labs(title = "UFO Sightings Per Year",
       x = "Year",
       y = "Numberof Sightings") +
  theme_minimal()
```

### Report by State

```{r}
data("usgeojson")

ufo_by_state = ufo_subset |>
  group_by(state) |>
  summarize(sightings = n())



# Define a lookup table for state abbreviations to full names
state_lookup = tibble(
  abbreviation = c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", 
                   "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", 
                   "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", 
                   "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", 
                   "UT", "VT", "VA", "WA", "WV", "WI", "WY", "PR"),
  full_name = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", 
                "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", 
                "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", 
                "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
                "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", 
                "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
                "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", 
                "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", 
                "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "Puerto Rico")
)

# Join this lookup table with your ufo_by_state data to get full state names
ufo_by_state = ufo_by_state |>
  left_join(state_lookup, by = c("state" = "abbreviation"))


            

n =  4
colstops = data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) |>
  list_parse2()

highchart() |>
  hc_add_series_map(usgeojson, ufo_by_state, name = "",
                    value = "sightings", joinBy = c("woename", "full_name"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) |>
  hc_colorAxis(stops = colstops) |>
  hc_legend(valueDecimals = 0, valueSuffix = "%") |>
  hc_mapNavigation(enabled = TRUE) |>
  hc_add_theme(thm)
```

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Report by Shape

```{r, fig.keep ='none'}
shape_distribution = ufo_subset |>
  count(shape) |>
  arrange(desc(n)) |>
  mutate(category = "UFO Shapes",
         subcategory = shape)


set.seed(10)

# Create a treemap
tm = treemap(
  shape_distribution, index = c("category", "subcategory"),
  vSize = "n",
  vColor = "n",
  type = "value",
  palette = rev(viridis(6)))

# Visualize
hctreemap(tm, allowDrillToNode = TRUE,
          layoutAlgorithm = "squarified") |>
  hc_add_theme(hc_theme_darkunica())
```


### Top 10 State

```{r}
top_states_ufo = ufo_subset |>
  count(state, name = "count") |>
  arrange(desc(count)) |>
  slice_head(n = 10) 

set.seed(2)

top_states_ufo |>
  hchart("bar", hcaes(x = state, y = count, group = state),
         showInLegend = FALSE, name = "UFO Sightings", 
         pointWidth = 10) |>
  hc_add_theme(hc_theme_darkunica()) |>
  hc_title(text = "Top 5 States by UFO Sightings") |>
  hc_xAxis(title = list(text = "State")) |>
  hc_yAxis(title = list(text = "Count of Sightings")) |>
  hc_plotOptions(bar = list(dataLabels = list(enabled = TRUE)))
```

### Report Frequency and Average Duration by State Map

```{r}
usaMap <- map_data("state")

clean_df = read_csv("ufo_clean_fin.csv") |>
  drop_na() |>
  group_by(state) |>
  summarize(report_freq = n(), avg_duration = mean(duration_clean))

cen_df = read_csv("us_census.csv") |> 
  select(abbrv, census_2010, census_2020) |> 
  rename(state = abbrv)

clean_df_combined = left_join(clean_df, cen_df, by = c("state")) |>
  mutate(report_freq_per_100k = (report_freq / census_2010)*100000) |>
  rename(abbrev = state)

state_names = read_csv("table-data.csv") |> select(state, code) |>
  rename(abbrev = code)

fin_clean_df = left_join(clean_df_combined, state_names, by = c("abbrev")) |> 
  select("state", everything()) |>
  mutate(census_2010 = census_2010 / 100)


which_state <- function(mapData, long, lat) {
  # This function decide the state being clicked. 
  #
  # Args:
  #   mapData: The map data has a column "long" and a column "lat" to determine
  #       state borders. 
  #   long, lat: longitude and latitude of the clicked point. They are actually
  #       input$clickMap$x and input$clickMap$y assuming click = "clickMap".
  #
  # Returns: 
  #   The name of the state containing the point (long, lat).
  
  # calculate the difference in long and lat of the border with respect to this point
  mapData$long_diff <- mapData$long - long
  mapData$lat_diff <- mapData$lat - lat
  
  # only compare borders near the clicked point to save computing time
  mapData <- mapData[abs(mapData$long_diff) < 20 & abs(mapData$lat_diff) < 15, ]
  
  # calculate the angle between the vector from this clicked point to border and c(1, 0)
  vLong <- mapData$long_diff
  vLat <- mapData$lat_diff
  mapData$angle <- acos(vLong / sqrt(vLong^2 + vLat^2))
  
  # calculate range of the angle and select the state with largest range
  rangeAngle <- tapply(mapData$angle, mapData$region, function(x) max(x) - min(x))
  return(names(sort(rangeAngle, decreasing = TRUE))[1])
}

# build the app

plotMap <- ggplot(usaMap, aes(x = long, y = lat, group = group)) + 
  geom_polygon(fill = "white", color = "black")

plotReport_Duration <- ggplot(fin_clean_df, aes(x = report_freq_per_100k, y = avg_duration)) + 
  geom_point(aes(size = census_2010, color = census_2010)) + 
  scale_size(limits = c(1, 1000000))

# Define UI for application that draws a histogram
ui <- shinyUI(fluidPage(
  column(
    width = 6,
    plotOutput("map", click = "clickMap", width = 430, height = 275)
  ),
  column(
    width = 6,
    plotOutput("ufo", width = 430, height = 275)
  )

    # # Application title
    # titlePanel("Old Faithful Geyser Data"),
    # 
    # # Sidebar with a slider input for number of bins 
    # sidebarLayout(
    #     sidebarPanel(
    #         sliderInput("bins",
    #                     "Number of bins:",
    #                     min = 1,
    #                     max = 50,
    #                     value = 30)
    #     ),
    # 
    #     # Show a plot of the generated distribution
    #     mainPanel(
    #        plotOutput("distPlot")
    #     )
    # )
))

# Define server logic required to draw a histogram
server <- shinyServer(function(input, output) {
  # intital plots
  output$map <- renderPlot({
    plotMap
    # coord_map(), do not use it. More discussion next section.
  })
  output$ufo <- renderPlot({
    plotReport_Duration
  })
  
  # plot after click
  observeEvent(input$clickMap, {
    xClick <- input$clickMap$x
    yClick <- input$clickMap$y
    state <- which_state(usaMap, xClick, yClick)
    output$map <- renderPlot(
      plotMap + 
        geom_polygon(data = usaMap[usaMap$region == state,], fill = "yellow") +
        annotate("text", x = xClick, y = yClick, label = state, color = "red")
    )
    output$ufo <- renderPlot({
      plotReport_Duration +
        geom_point(data = fin_clean_df[tolower(fin_clean_df$state) == state,],
                   size = 6, shape = 2, color = "red")
    })
  })
})

    # output$distPlot <- renderPlot({
    #     # generate bins based on input$bins from ui.R
    #     x    <- faithful[, 2]
    #     bins <- seq(min(x), max(x), length.out = input$bins + 1)
    # 
    #     # draw the histogram with the specified number of bins
    #     hist(x, breaks = bins, col = 'darkgray', border = 'white',
    #          xlab = 'Waiting time to next eruption (in mins)',
    #          main = 'Histogram of waiting times')
    # })
```
